import type { FeedbackTheme } from '@kobecuppens/feedback-core';
import { Platform, StyleSheet, type TextStyle, type ViewStyle } from 'react-native';

/**
 * Every styleable part of the board. Pass `styles={{ card: {...} }}` to
 * `<FeedbackBoard>` to override one; the override is merged over the themed base.
 */
export const SLOT_NAMES = [
  'container',
  'header',
  'headerTitle',
  'backButton',
  'backButtonText',
  'tabBar',
  'tab',
  'tabActive',
  'tabText',
  'tabTextActive',
  'tabBadge',
  'tabBadgeText',
  'toolbar',
  'searchInput',
  'chipRow',
  'chip',
  'chipActive',
  'chipText',
  'chipTextActive',
  'list',
  'listContent',
  'card',
  'cardPending',
  'cardBody',
  'cardTitle',
  'cardExcerpt',
  'cardMeta',
  'cardMetaText',
  'voteBox',
  'voteButton',
  'voteButtonActive',
  'voteArrow',
  'voteArrowActive',
  'voteCount',
  'statusPill',
  'statusPillText',
  'categoryPill',
  'categoryPillText',
  'moderationBanner',
  'moderationBannerText',
  'button',
  'buttonText',
  'buttonSecondary',
  'buttonSecondaryText',
  'buttonDanger',
  'buttonDangerText',
  'buttonDisabled',
  'fab',
  'fabText',
  'form',
  'inputLabel',
  'input',
  'textarea',
  'helperText',
  'errorText',
  'detail',
  'detailTitle',
  'detailBody',
  'attachmentRow',
  'attachmentImage',
  'sectionTitle',
  'commentItem',
  'commentOfficial',
  'commentHeader',
  'commentAuthor',
  'commentTime',
  'commentBody',
  'officialBadge',
  'officialBadgeText',
  'composer',
  'composerInput',
  'avatar',
  'avatarText',
  'empty',
  'emptyText',
  'loading',
  'roadmapScroll',
  'roadmapColumn',
  'roadmapColumnHeader',
  'roadmapColumnTitle',
  'roadmapCount',
  'roadmapCard',
  'roadmapCardTitle',
  'updateItem',
  'updateKind',
  'updateTitle',
  'adminBar',
  'adminRow',
] as const;

export type SlotName = (typeof SLOT_NAMES)[number];
/** Text styles are a superset of view styles, so one type fits every slot. */
export type SlotStyle = TextStyle;
export type FeedbackStyles = Partial<Record<SlotName, SlotStyle>>;

export function makeBaseStyles(t: FeedbackTheme): Record<SlotName, SlotStyle> {
  const c = t.colors;
  const s = t.spacing;
  const f = t.fonts;
  const text = (size: number, weight: TextStyle['fontWeight'] = f.weights.regular, color = c.text): TextStyle => ({
    fontSize: size,
    fontWeight: weight,
    color,
    ...(f.body ? { fontFamily: f.body } : null),
  });
  const heading = (size: number): TextStyle => ({
    ...text(size, f.weights.bold),
    ...(f.heading ? { fontFamily: f.heading } : null),
  });
  const cardShadow: ViewStyle =
    t.shadow.elevation > 0
      ? Platform.select<ViewStyle>({
          android: { elevation: t.shadow.elevation },
          web: { boxShadow: t.shadow.card } as ViewStyle,
          default: {
            shadowColor: '#000',
            shadowOpacity: 0.06,
            shadowRadius: 2,
            shadowOffset: { width: 0, height: 1 },
          },
        })
      : {};
  const pill: ViewStyle = {
    alignSelf: 'flex-start',
    paddingHorizontal: s.sm,
    paddingVertical: 2,
    borderRadius: t.radii.pill,
  };
  const button: ViewStyle = {
    minHeight: 44,
    paddingHorizontal: s.lg,
    borderRadius: t.radii.md,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  };
  const input: SlotStyle = {
    ...text(f.sizes.md),
    backgroundColor: c.surface,
    borderWidth: StyleSheet.hairlineWidth * 2,
    borderColor: c.border,
    borderRadius: t.radii.md,
    paddingHorizontal: s.md,
    paddingVertical: s.sm + 2,
  };

  return {
    container: { flex: 1, backgroundColor: c.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: s.lg,
      paddingVertical: s.md,
      gap: s.sm,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
      backgroundColor: c.surface,
    },
    headerTitle: { ...heading(f.sizes.lg), flex: 1 },
    backButton: { paddingVertical: s.xs, paddingRight: s.sm, minHeight: 44, justifyContent: 'center' },
    backButtonText: text(f.sizes.md, f.weights.medium, c.primary),
    tabBar: {
      flexDirection: 'row',
      paddingHorizontal: s.md,
      paddingTop: s.sm,
      gap: s.xs,
      backgroundColor: c.surface,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
    },
    tab: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: s.xs,
      paddingHorizontal: s.md,
      paddingVertical: s.sm + 2,
      borderBottomWidth: 2,
      borderBottomColor: 'transparent',
    },
    tabActive: { borderBottomColor: c.primary },
    tabText: text(f.sizes.sm, f.weights.medium, c.textMuted),
    tabTextActive: { color: c.text },
    tabBadge: {
      minWidth: 18,
      height: 18,
      borderRadius: 9,
      paddingHorizontal: 5,
      backgroundColor: c.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tabBadgeText: text(f.sizes.xs, f.weights.bold, c.onPrimary),
    toolbar: { paddingHorizontal: s.lg, paddingTop: s.md, gap: s.sm },
    searchInput: input,
    chipRow: { flexDirection: 'row', gap: s.xs, paddingVertical: s.xs },
    chip: {
      paddingHorizontal: s.md,
      paddingVertical: s.xs + 2,
      borderRadius: t.radii.pill,
      borderWidth: StyleSheet.hairlineWidth * 2,
      borderColor: c.border,
      backgroundColor: c.surface,
    },
    chipActive: { backgroundColor: c.primary, borderColor: c.primary },
    chipText: text(f.sizes.sm, f.weights.medium, c.textMuted),
    chipTextActive: { color: c.onPrimary },
    list: { flex: 1 },
    listContent: { padding: s.lg, gap: s.md, paddingBottom: 96 },
    card: {
      flexDirection: 'row',
      gap: s.md,
      padding: s.md,
      borderRadius: t.radii.lg,
      backgroundColor: c.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      ...cardShadow,
    },
    cardPending: { borderStyle: 'dashed', borderColor: c.status.pending },
    cardBody: { flex: 1, gap: s.xs },
    cardTitle: heading(f.sizes.md),
    cardExcerpt: text(f.sizes.sm, f.weights.regular, c.textMuted),
    cardMeta: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: s.sm, marginTop: s.xs },
    cardMetaText: text(f.sizes.xs, f.weights.regular, c.textMuted),
    voteBox: { alignItems: 'center', minWidth: 44, gap: 2 },
    voteButton: {
      width: 44,
      height: 32,
      borderRadius: t.radii.sm,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.surfaceAlt,
    },
    voteButtonActive: { backgroundColor: c.primary },
    voteArrow: text(f.sizes.sm, f.weights.bold, c.textMuted),
    voteArrowActive: { color: c.onPrimary },
    voteCount: { ...text(f.sizes.md, f.weights.bold), textAlign: 'center' },
    statusPill: { ...pill, backgroundColor: c.surfaceAlt },
    statusPillText: text(f.sizes.xs, f.weights.bold),
    categoryPill: { ...pill, backgroundColor: c.surfaceAlt },
    categoryPillText: text(f.sizes.xs, f.weights.medium, c.textMuted),
    moderationBanner: {
      padding: s.md,
      borderRadius: t.radii.md,
      backgroundColor: c.surfaceAlt,
      borderLeftWidth: 3,
      borderLeftColor: c.status.pending,
    },
    moderationBannerText: text(f.sizes.sm),
    button: { ...button, backgroundColor: c.primary },
    buttonText: text(f.sizes.md, f.weights.bold, c.onPrimary),
    buttonSecondary: { ...button, backgroundColor: c.surfaceAlt },
    buttonSecondaryText: text(f.sizes.md, f.weights.medium, c.text),
    buttonDanger: { ...button, backgroundColor: c.danger },
    buttonDangerText: text(f.sizes.md, f.weights.bold, c.onDanger),
    buttonDisabled: { opacity: 0.5 },
    fab: {
      position: 'absolute',
      right: s.lg,
      bottom: s.xl,
      ...button,
      borderRadius: t.radii.pill,
      backgroundColor: c.primary,
      paddingHorizontal: s.xl,
      ...cardShadow,
    },
    fabText: text(f.sizes.md, f.weights.bold, c.onPrimary),
    form: { padding: s.lg, gap: s.md },
    inputLabel: text(f.sizes.sm, f.weights.medium),
    input,
    textarea: { ...input, minHeight: 120, textAlignVertical: 'top' },
    helperText: text(f.sizes.xs, f.weights.regular, c.textMuted),
    errorText: text(f.sizes.sm, f.weights.medium, c.danger),
    detail: { padding: s.lg, gap: s.md, paddingBottom: 120 },
    detailTitle: heading(f.sizes.xl),
    detailBody: { ...text(f.sizes.md), lineHeight: f.sizes.md * 1.45 },
    attachmentRow: { flexDirection: 'row', flexWrap: 'wrap', gap: s.sm },
    attachmentImage: { width: 96, height: 96, borderRadius: t.radii.md, backgroundColor: c.surfaceAlt },
    sectionTitle: { ...heading(f.sizes.md), marginTop: s.md },
    commentItem: {
      padding: s.md,
      borderRadius: t.radii.md,
      backgroundColor: c.surface,
      gap: s.xs,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
    },
    commentOfficial: { borderColor: c.primary, borderWidth: 1 },
    commentHeader: { flexDirection: 'row', alignItems: 'center', gap: s.sm },
    commentAuthor: text(f.sizes.sm, f.weights.bold),
    commentTime: text(f.sizes.xs, f.weights.regular, c.textMuted),
    commentBody: { ...text(f.sizes.md), lineHeight: f.sizes.md * 1.4 },
    officialBadge: { ...pill, backgroundColor: c.primary },
    officialBadgeText: text(f.sizes.xs, f.weights.bold, c.onPrimary),
    composer: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: s.sm,
      padding: s.md,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.border,
      backgroundColor: c.surface,
    },
    composerInput: { ...input, flex: 1, maxHeight: 120 },
    avatar: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: c.surfaceAlt,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    avatarText: text(f.sizes.xs, f.weights.bold, c.textMuted),
    empty: { padding: s.xl, alignItems: 'center', gap: s.md },
    emptyText: { ...text(f.sizes.md, f.weights.regular, c.textMuted), textAlign: 'center' },
    loading: { padding: s.xl, alignItems: 'center' },
    roadmapScroll: { padding: s.lg, gap: s.md },
    roadmapColumn: { width: 280, backgroundColor: c.surfaceAlt, borderRadius: t.radii.lg, padding: s.md, gap: s.sm },
    roadmapColumnHeader: { flexDirection: 'row', alignItems: 'center', gap: s.sm, marginBottom: s.xs },
    roadmapColumnTitle: heading(f.sizes.md),
    roadmapCount: text(f.sizes.sm, f.weights.medium, c.textMuted),
    roadmapCard: { padding: s.md, borderRadius: t.radii.md, backgroundColor: c.surface, gap: s.xs, ...cardShadow },
    roadmapCardTitle: text(f.sizes.sm, f.weights.bold),
    updateItem: {
      padding: s.md,
      borderRadius: t.radii.md,
      backgroundColor: c.surface,
      gap: s.xs,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
    },
    updateKind: text(f.sizes.xs, f.weights.bold, c.primary),
    updateTitle: text(f.sizes.md, f.weights.medium),
    adminBar: { gap: s.sm, padding: s.md, borderRadius: t.radii.md, backgroundColor: c.surfaceAlt },
    adminRow: { flexDirection: 'row', flexWrap: 'wrap', gap: s.sm },
  };
}

export function mergeStyles(base: Record<SlotName, SlotStyle>, overrides?: FeedbackStyles): Record<SlotName, SlotStyle> {
  if (!overrides) return base;
  const out = { ...base };
  for (const key of Object.keys(overrides) as SlotName[]) {
    out[key] = StyleSheet.flatten([base[key], overrides[key]]) as SlotStyle;
  }
  return out;
}
